name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: git clone
      run: git clone https://github.com/Kudaraidee/cpuminer-opt-kudaraidee
    - name: cpuminer-opt-kudaraidee
      run: cd cpuminer-opt-kudaraidee && chmod +x *.sh
    - name: build
      run: ./build.sh 
    
    
