name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: distclean
      run: make distclean || echo clean && rm -f config.status 
    - name: autogen
      run: set -e && aclocal && autoheader && automake --foreign --add-missing --force-missing --copy && autoconf
     - name: configure
      run: ./configure --with-curl CFLAGS="-O3 -march=native -Wall"
    - name: make
      run: make -j 4
    - name: strip cpuminer
      run: strip -s cpuminer
    
