name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: autogen
      run: ./autogen.sh 
    - name: configure
      run: ./configure --with-curl CFLAGS="-O3 -march=native -Wall"
    - name: make
      run: make -j 4
    - name: strip cpuminer
      run: strip -s cpuminer
    
